# Generated by Django 2.2.4 on 2019-10-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sterling',
            field=models.IntegerField(default=1000),
        ),
    ]
