# Generated by Django 2.2.4 on 2019-10-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_sterling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sterling',
            field=models.IntegerField(default=10000),
        ),
    ]
