# Generated by Django 2.2.4 on 2019-10-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Содержимое')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Описание')),
                ('first_option', models.TextField(default='', verbose_name='Первый вариант ответа')),
                ('second_option', models.TextField(default='', verbose_name='Второй вариант ответа')),
                ('third_option', models.TextField(default='', verbose_name='Третий вариант ответа')),
                ('fourth_option', models.TextField(default='', verbose_name='Четвертый вариант ответа')),
                ('correct_option', models.CharField(choices=[('first_choice', 'Первый вариант'), ('second_choice', 'Второй вариант')], default='first_choice', max_length=1)),
                ('task_difficulty', models.SmallIntegerField(default=0, max_length=10, verbose_name='Сложность')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('Сложность', models.SmallIntegerField(max_length=10)),
                ('Текст задачи', models.TextField()),
                ('coins', models.IntegerField(default=0, max_length=9999, verbose_name='Ценность')),
                ('publication_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
