# Generated by Django 2.2.4 on 2019-10-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191013_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='couser',
            new_name='course',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='Сложность',
        ),
        migrations.AddField(
            model_name='problem',
            name='task_difficulty',
            field=models.SmallIntegerField(default=0, max_length=10, verbose_name='Сложность'),
        ),
    ]
