# Generated by Django 2.2.4 on 2019-10-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191013_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='correct_option',
            field=models.CharField(choices=[('first_choice', 'Первый вариант'), ('second_choice', 'Второй вариант')], default='first_choice', max_length=50),
        ),
    ]
